export const THUMB_UP = 'THUMB_UP'
export const THUMB_DOWN = 'THUMB_DOWN'
export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COLLECTION = 'ADD_COLLECTION'
export const CHANGE_COLOR = 'CHANGE_COLOR'
export const SET_TOKEN = 'SET_TOKEN'
export const GET_TOKEN = 'GET_TOKEN'
export const DELETE_TOKEN = 'DELETE_TOKEN'
